### ISSUE TITLE
Is it possible to highlight the cursor coordinates area on screenshot?

### ISSUE THREAD

**Issue by Kai-Tipalti** [Evilweed/protractor-beautiful-reporter#182]
It would be useful and time saving to see from the first glance which element of the dom was interacted with right before the failure occurred.

**Comment by miller45** [comment]
That seems to be a very hard thing, because protractor does not help find out what active element is. Maybe you can add a text to the expects like `expect(xy).toBe("hello","in textbox with user name")`.

I found a plugin for showing the mouse position and adapted it to new protractor. But only works if you work with mousemove command. 
Look here and try it out: https://gist.github.com/miller45/c187ea399317cde2320736f4c80a9ba8

**Comment by Kai-Tipalti** [comment]
Thank you very much for a swift reply!
Unfortunately we do not user mousemove.
I guess I'll try to find some solution on our end.
We like protractor-beautiful-reporter never the less :)
