### ISSUE TITLE
Add compatibility for UTF-8

### ISSUE THREAD

**Issue by JiggyJinjo** [Evilweed/protractor-beautiful-reporter#41]
Hi, 
thanks for your work ! 
I encounter an issue where I need to have accented characters in my it description but the reports is failing with them : 

![image](https://user-images.githubusercontent.com/36196067/35972804-8d3d0c46-0cd3-11e8-9fb0-87a211917fd5.png)

Is there a way to fix this ?

Thanks in advance

**Comment by Evilweed** [comment]
I will dig into this in free time (unless someone else would like to do PR).

**Comment by Evilweed** [comment]
@JiggyJinjo You have used function that generates filenames using descriptions (similar to this one):
```
new HtmlReporter({
   baseDirectory: 'tmp/screenshots'
   , pathBuilder: function pathBuilder(spec, descriptions, results, capabilities) {
      return path.join(capabilities.caps_.browser, descriptions.join('-'));
   }
});
```

Because of this my script tries to save file with name 'IRIS-123 - bla bla "code modéle" bla bla'.

Please either remove this "pathBuilder" from your protractor.conf, or change it so that You remove special characters from the generated file name.
