### ISSUE TITLE
ReferenceError: browser is not defined when using protractor with typescript

### ISSUE THREAD

**Issue by technodeath** [Evilweed/protractor-beautiful-reporter#47]
Solution: add in index.js

let globals = require('protractor');
let browser = globals.browser;

**Comment by technodeath** [comment]
Note: it reproduced for TypeScript users with option noGlobals: true in protractor config

**Comment by Evilweed** [comment]
@technodeath You have created PR but in it You are editing compiled file instead source file - if you want it to be merged, then you need to create fix in source files.

**Comment by miller45** [comment]
Workaround: Just set noGlobals: false

**Comment by sopelt** [comment]
@Evilweed @miller45  I am not sure how many people might be impacted by this scenario but I would like to reopen this to discuss it further (or do a second issue?).
When using jasmine + protractor + typescript I was unable to fully get the reporter to work. Without noGlobals: false there is the obvious, initial issue. When having noGlobals: false (which I would like to avoid) I still fail in many cases. E.g. when restarting the browser or having the browser closed for a few tests in between. The reporting seems to fail for all subsequent tests due to `NoSuchSessionError: invalid session id`. I suspect that something changes in the `protractor.browser` instance that is not reflected in the global `browser`.
Should I try and create a minimal repro for that? Do you have ideas on how to approach a fix?

Thanks!
