### ISSUE TITLE
Console.log showing on reporter

### ISSUE THREAD

**Issue by pederjohn** [Evilweed/protractor-beautiful-reporter#76]
I don't know if there is a possibility to show the console log in the reporter, I for instance console log an elements text value but it doesn't pull through to the reporter.

**Comment by miller45** [comment]
@pederjohn you have to set  gatherBrowserLogs: true... See search in readme.md for exact details. 
You can then look at these messages in the "Browser Errors" Column when you click on the red or orange number...

**Comment by miller45** [comment]
For me it seems to be that the logging is happening in your e2e test code and not in your actual application code.
The gatherBrowserLogs only catches logs that occurs inside the browser that is by design. 
If you want to have it "fast" you could do something like 
browser.executeScript('console.log("8 Header Name: Send E-Mail"');

**Comment by pederjohn** [comment]
Thanks @miller45 I appreciate it, will see what I can do.
